#!/usr/bin/env perl

use 5.010;
use warnings;
use strict;

my $fdisk = sub {
    my $disk = shift;
    die if $disk eq "sda";
    my @seq = ("d\n","\n","d\n","\n","d\n","\n","w\n");
    open my $p,"|-","fdisk /dev/$disk";
    print $p $_ for @seq;
    close $p;

    system("partprobe /dev/$disk");
    say '-----------';
    say `lsblk`;
};

#my $disk = <>;
my $disk = 'sdb';
chomp $disk;

system("vgremove vg_a");
push my @pvs, `pvs --noheadings -o NAME`;
for(@pvs){ chomp; system("pvremove $_") };

$fdisk->($disk);

