#!/usr/bin/env perl

use 5.010;
use warnings;
use strict;

use File::Copy;
use Data::Dumper;

chomp(my $arch = `uname -n`);
# find package which cmd belongs to "dpkg -S cmd"
my $conf = sub {
    my $c = {};

    $c = {
        id => "#github.com/z448/perls/$0",
        dotfile => "$ENV{HOME}/.bashrc",
        apps => {
            debian =>  [ 'xsel', 'xclip', 'x11-xkb-utils', 'x11-apps' ],
        },
        dots => [],
        data => [],
    };
    while( <DATA> ){ chomp $_; push @{ $c->{data} }, $_  }
# backup previous .bashrc
    copy($c->{dotfile}, "$c->{dotfile}.bak");

# read .bashrc content except old DATA
    my $f = 0;
    open(my $fh,'<',$c->{dotfile}) || die "cant open $c->{dotfile}: $!";
    while( <$fh> ){ 
        chomp;
        if( $_ eq "$c->{id}#start" ){ $f = 1 }
        push @{ $c->{dots} }, $_ unless $f == 1;
        if( $_ eq "$c->{id}#end" ){ $f = 0 }
    }
    close $fh;
    return $c;
};


my $write = sub {
    my $c = $conf->();
    open(my $fh,'>',$c->{dotfile}) || die "cant open $c->{dotfile}: $!";
    say $fh $_ for @{ $c->{dots}};
    say $fh "$c->{id}#start";
    say $fh $_ for @{ $c->{data}};
    say $fh "$c->{id}#end";
    close $fh;
    return $c;
};

my $install = sub {
    my $arch = shift;
    my $a = $conf->();
    return sub { for( @{ $a->{apps}->{$arch} } ){ `apt-get install $_` } };
};

=head1
my %ini = ();

my $arch = {
    for(`uname -a`){
        chomp $_;
        return 'Ubutnu' if $_ =~ /ubuntu/;
        return 'iPhone' if $_ =~ /iphone/;
        return 'darwin' if $_ =~ /osx/;
    }
};

my %conf = ();
$conf{arch} ;
=cut

#my $c = $install->($arch);
#print $c->();

$write->();
=head1 TODO

alias/bind for apt-cache search, apt-get install ..

script to git clone when you'll connected/disconnected from home wifi

=cut
__DATA__

# setup dots
perl -E 'if(-f "$ENV{HOME}/Documents/perls/setup"){ system("$ENV{HOME}/Documents/perls/setup ~/local/bin") }'

# set vi mode on command line
set -o vi

# set vi as default editor
export EDITOR=vi

# vim will use custom config in $MYVIMRC
export MYVIMRC=~/.vimrc

#NOTE: i set colorscheme in .vimrc to ir_black then use Grey On Black built-in scheme with Solarized palette in Gnome Terminnal (Terminal->Preferences->Profiles->Edit->Color)

# add ~/local/bin to PATH
export PATH=~/local/bin:$PATH

# set locale to UTF-8
export LC_ALL="en_US.UTF-8"

# CTRL-P will switch me into ~/dpp dir; doesnt work when sourced from bashrc; must be added into ~/.bashrc file
bind '"\C-p":"dclear\n"';
bind '"\C-g":"cd ~/Documents/dpp/App-dpp-1.0 && pwd\n"';

# remap CAPS_LOCK to CTRL on linux
perl -E 'if(`which setxkbmap`){ `setxkbmap -option \"caps:ctrl_modifier\"`}'

# + also remap CAPS_LOCK to ESC on linux (usefull in vim)
#perl -E 'if(`which xcape`){ `xcape -e \"Caps_Lock=Escape\"`}'

# p alias for perl one-liners
alias p="perl -E '\
use 5.010;
use warnings;
use strict;

use Data::Dumper;
use JSON::PP;
"

# mount HFS+ external disk
# apt-get install hfsprogs
# mount -t hfsplus -o force,rw /dev/sdb3 /1T
# chmod -R 775 /1T
# chown -R zdenek:zdenek /1T
#
