#!/usr/bin/env perl

use 5.010;
use warnings;
use strict;

use Config;

my $module_version = sub {
    my $module = shift;
    for my $instpath( qw< installsitelib installsitearch > ){
        $module =~ s/\:\:/\//g; 
        next unless -f "$Config{$instpath}/$module.pm";
        open(my $fh,'<',"$Config{$instpath}/$module.pm") || die "cant open: $!";
        while( <$fh> ){
            if(/(\:|\$)(VERSION)(.*?\=)(.*?)([0-9].*?)(\s|'|"|;)(.*)/){ return $5 }
        }
    }
    return "$ARGV[0] module is not installed in $Config{installsitelib} or $Config{installsitearch}";
};

unless( @ARGV ){ system("perldoc $0"); exit }
say $module_version->("$ARGV[0]");

=head1

NAME

get_module_version - find version of perl5 module installed from cpan 

USAGE

C<get_module_version Module::Name >

=cut
