#!/usr/bin/env perl

use 5.010;
use warnings;
use strict;

use Data::Dumper;
use HTTP::Tiny;

my $get = sub {
    my $name = shift;
    my %g = (
        url => 'https://metacpan.org/pod/',
        name => $name,
        agent => 'Mozilla/5.0',
    );

    my $res;
    #return sub{ $res = HTTP::Tiny->new->get("$g{url}$g{name}"); return $res->{content} } if HTTP::Tiny->can_ssl;
    return sub{
        open my $p,'-|',"curl --user-agent \"$g{agent}\" -skL '$g{url}$g{name}'";
        while( <$p> ){ $res .= $_ }
        return $res;
    };
};


my $version_path = sub {
    my $module = shift;
    my $res = $get->($module);
    my $field = 0;
    my %version = ();

    open(my $fh,'<',\$res->());
    while( <$fh> ){
        if(/Jump to version/){ $field = 1 }
        if( /(value|label)\=\"(.*?)\/(.*?)\/.*">(.*?)\ / ){
                $version{"$4"} = "$2/$3" unless $field == 0;
        }
    }
    return \%version;
};

my $p = $version_path->("$ARGV[0]");
if( defined $ARGV[1] ){ say $p->{$ARGV[1]} . '.tar.gz' }
else { print Dumper $p }

=head1

NAME

version_path - prints array of hashes author=>path/to/version/module

USAGE

version_path Module::Name

DEPENDENCIES

libssl

=cut

